title: Joseph Lam
name: Joseph Lam
description: Projects by Joseph Lam — Bible Verse Memorizer, PrayChrist, HopeWeave, and more.
theme: minima
markdown: kramdown
plugins:
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

